### ISSUE TITLE
Mention in the README that this is an OSX-only app

### ISSUE THREAD

**Issue by bjohnso5** [sakamies/ranui#3]
`npm start` fails on Windows - seems to be related to assuming a Dock exists.

**Comment by sakamies** [comment]
Ah right, no reason to keep this a Mac only app with electron. The final app platform(s) will depend on what kind of contributors we can find though.

**Comment by sakamies** [comment]
Oh man, multiplatform keyboard combo support isn't so simple after all. I'll make this macOS only for the time being so I can make progress faster. I'll expand platform support when I have time or get contributions for it.
