### ISSUE TITLE
Links to Foolproof HTML blog with query params return a 404 response.

### ISSUE THREAD

**Issue by tomsabin** [sakamies/ranui#5]
I recently found your post about Foolproof HTML from the weekly Hacker Newsletter email, however, the link to the article is broken when there are query parameters. This issue might be in the incorrect place but it's the best way I can make you aware of the problem in detail. If you are aware already, please feel free to close this.

The Hacker Newsletter has the following link

> ![screen shot 2017-02-13 at 09 54 00](https://cloud.githubusercontent.com/assets/885223/22878703/b357a91c-f1d2-11e6-8191-e1a3203b8c36.png)

which redirects to the URL with UTM query params:

```
https://pumpula.net/foolproof-html?utm_source=hackernewsletter&utm_medium=email&utm_term=code
```

However, when you visit this URL you'll receive a 404 response:

> ![screen shot 2017-02-13 at 09 54 19](https://cloud.githubusercontent.com/assets/885223/22878747/dac8062c-f1d2-11e6-89c7-a1f1107071e0.png)

The same will happen for any query parameter, even just [`https://pumpula.net/foolproof-html?`](https://pumpula.net/foolproof-html?)

You're likely to be missing out on some visitors from the broken URL on the Hacker Newsletter email.

**Comment by sakamies** [comment]
Well that's just wrong, one more reason why I should stick to ready made site engines. Should be fixed now. Thank you!
