### ISSUE TITLE
How to start contributing

### ISSUE THREAD

**Issue by matthewfcarlson** [sakamies/ranui#6]
Came across the HackerNews article. I love the idea and would love to contribute. What needs to get done? What is the vision?

**Comment by sakamies** [comment]
The grand idea is to build a native html editor that can handle any html. Then hopefully expand the editing model to support css, then json and others.

My prototype code is a mess, so we're trying to get some proper app arcitecture done. I set up a gitter chat, planning  and sharing stuff there is the best way to contribute right now. Come on in. :)

<https://gitter.im/flprf/Lobby>

**Comment by sakamies** [comment]
I added my reply to the readme too, so thanks for asking. :)
